### ISSUE TITLE
Iterm2 Colors look weird

### ISSUE THREAD

**Issue by GautamBose** [kepano/flexoki#12]
I just imported the iterm2 theme and things are looking a little off:

<img width="682" alt="Screenshot 2023-10-09 at 10 55 59 AM" src="https://github.com/kepano/flexoki/assets/8022792/9a6f6deb-a0bc-4b80-99e8-70e68c05fdc4">

What could be causing something like this?

**Comment by techvlad** [comment]
Colors should work, here's example with `bat` with ansi theme
<img width="682" alt="image" src="https://github.com/kepano/flexoki/assets/13676043/a513e063-21b1-4c61-9325-87ba082a11a4">
@GautamBose can you check which `colorscheme` and `background` are you using inside vim?
P.S. From my vim experience it's always better to use dedicated theme for vim [like this one](https://github.com/kepano/flexoki/tree/main/neovim)
