### ISSUE TITLE
Variations of dark themes

### ISSUE THREAD

**Issue by techvlad** [kepano/flexoki#14]
Flexoki color scheme provides multiple choices for dark background.

In my [iterm2 dark port](https://github.com/kepano/flexoki/blob/main/iterm2/flexoki_dark.itermcolors) I used 950 (#1C1B1A), color from [Obsidian Minimal theme ](https://github.com/kepano/obsidian-minimal).

Right now it's a best time to decide which dark color (or maybe multiple, like in [catppuccin](https://github.com/catppuccin/catppuccin?tab=readme-ov-file#-palette)) should be as base for dark color themes.

I don't have strong opinion, my script for generation iTerm2 themes will provide customisation anyways

**Comment by peterjbachman** [comment]
I tried to use the following table to guide my choices for making the Kitty themes. I based the light and dark themes off using the `bg` tag for the background and the selection background off the `ui-3` tag. The active and inactive tab backgrounds were `ui` and `ui-3` respectively while the tab foregrounds were `txt` and `txt-2`

<img width="802" alt="Screenshot 2023-10-09 at 2 51 23 PM" src="https://github.com/kepano/flexoki/assets/46987067/c4e5d0c8-853c-4b2c-b467-4fd2c7caeebe">

Variations won't be hard for me to make either, but I think this table provides a good starting point.

**Comment by kepano** [comment]
In dark mode the default background should be `black` (1000), but for people who prefer lower contrast `950` or `900` can work.

**Comment by itsTyrion** [comment]
TIL you can put hex colors in a GitHub reply o.O
