### ISSUE TITLE
Sidebars seem to be using dark theme on light theme selection.

### ISSUE THREAD

**Issue by johnzimmerman** [kepano/flexoki#15]
The left and right sidebars do not seem to be respecting the Flexoki color scheme on my personal vault. 

When I go into the Minimal Theme Settings plugin and set the Light mode color scheme to Flexoki, my left and right sidebars turn dark. (Look in the background, not the foreground.)

![CleanShot 2023-10-09 at 15 40 51](https://github.com/kepano/flexoki/assets/595923/9519f1e3-ac82-45cc-9ce1-aea7dbef246f)

However, when I use a fresh vault, your vault template for example, I don't experience this issue.

![CleanShot 2023-10-09 at 15 45 26](https://github.com/kepano/flexoki/assets/595923/0bebb20c-9dc5-4aeb-8608-b53c05fad121)

I don't use custom CSS, and I only experience this issue with the Flexoki theme. I've uninstalled the Minimal Theme and the Minimal Theme Settings plugin and restarted Obsidian (and my computer) to troubleshoot, but I get the same results when I reinstall both. 

Any idea what might be happening? 

I [tweeted](https://x.com/JohnZimmerman/status/1711459593522418066?s=20) about this issue as well, but I don't think I was clear on what to look for in the background. Please correct me if I'm wrong and this is the desired behavior. Thank you!

**Comment by kepano** [comment]
Please open this issue on the Minimal repo
