### ISSUE TITLE
MacOS Terminal Theme "Is Corrupt"

### ISSUE THREAD

**Issue by clickbrain** [kepano/flexoki#23]
MacOS responds that your terminal theme is corrupt when trying to open it.

**Comment by getninjaN** [comment]
> MacOS responds that your terminal theme is corrupt when trying to open it.

I exported it from the Terminal settings. Hmm, I'll take a look.

**Comment by getninjaN** [comment]
@clickbrain what version of macOS are you using? I duplicated the Dracula theme when creating this one and I'm thinking it could be the font that makes it corrupt?

One commit in that repo was changing the font as a macOS Mojave update.

**Comment by tklai** [comment]
Hi @clickbrain

Are you simply double click the terminal after you downloaded the file?
You may need to right click the file and click "Open" to import from Finder, or import via Terminal Settings.

**Comment by clickbrain** [comment]
@getninjaN 
I'm running Sonoma 14.1. Thanks for checking. 

@tklai Thanks. 
Here's a screenvid of what I see when I try to import/open it. 
https://monosnap.com/file/Hc6CepuQExlVIzPoHoB6LGuTm4RcL0

**Comment by clickbrain** [comment]
https://github.com/kepano/flexoki/assets/963889/645dd150-363e-41bd-8906-be9e2cbebe6b

**Comment by tklai** [comment]
@clickbrain 
Cc. @getninjaN 

Not sure if it is color profile issue. Can you try the terminal files from my PR #68?

**Comment by tklai** [comment]
Looked into some terminal theme repositories around GitHub and found this issue may relates to macOS security mechanism.
When users download a file from the internet, macOS attaches a flag `com.apple.quarantine` to prevent opening the files directly without user consents. 

However, you can try the following command to remove the flag.
```
xattr -d com.apple.quarantine {the_file}
```
| Part | Explanation |
| :---: | --- |
| `xattr` | A macOS tool which manage extended attributes |
| `-d` | A flag that tell the tool to delete an attribute |
| `com.apple.quarantine` | The attribute that triggers macOS security mechanism |
| `{the_file}` | The file you want to process |
