### ISSUE TITLE
iTerm2: Light theme with color issues

### ISSUE THREAD

**Issue by gilsondev** [kepano/flexoki#26]
When using the light mode in iTerm2, the prompt in the spaceship theme has text colors that are the same as the background. Please refer to the attached images for reference.

![CleanShot 2023-10-10 at 11 42 57@2x](https://github.com/kepano/flexoki/assets/265653/0535650c-a53d-478e-8ee5-8e9dc2c7eccd)

![CleanShot 2023-10-10 at 11 43 20@2x](https://github.com/kepano/flexoki/assets/265653/c1b3233c-af0e-485d-9e70-466bb5e6f6de)

**Comment by gilsondev** [comment]
Not work unfortunely. Using the dimmed version:

![CleanShot 2023-10-10 at 16 01 32@2x](https://github.com/kepano/flexoki/assets/265653/3c311cb4-6fdb-4b75-86a1-f9a33902d558)

I restart the iTerm and refreshed the prompt session.

**Comment by techvlad** [comment]
https://github.com/kepano/flexoki/pull/35
Try this version, I fixed some bugs.
Also you can try to override white color by using `SPACESHIP_AWS_COLOR` env variable
Spaceship is using color `208` (TBH I don't know what it's means, for node env they using `green` color)
https://spaceship-prompt.sh/sections/aws/

**Comment by gilsondev** [comment]
Thanks, I'll try again
