### ISSUE TITLE
markdown.heading missing in VS Code theme

### ISSUE THREAD

**Issue by TomMoeras** [kepano/flexoki#36]
The `markdown.heading` scope appears to be missing from the `Flexoki-Dark-color-theme.json` file. When using a markdown heading like `# Heading`, the heading is white.
<img width="263" alt="markdown_heading_scope_missing1" src="https://github.com/kepano/flexoki/assets/68426187/781c40b0-a874-4a03-b06d-31493c4f9d08">

I've manually added the `markdown.heading` scope to my JSON file. However, I've noticed that the "#" still remains in the default white color instead of the heading color.
<img width="250" alt="markdown_heading_scope_missing2" src="https://github.com/kepano/flexoki/assets/68426187/ab318c3f-2106-49db-b9af-05c652ade98c">

**Comment by Railly** [comment]
I was using `entity.name.section.markdown` for matching that token. I can add `markdown.heading`, but can you show me your textmate scopes for both the "#" and the heading? Just like this:

![image](https://github.com/kepano/flexoki/assets/51397083/75b32f23-1424-4a7f-9348-d9ba7d0464fe)

**Comment by TomMoeras** [comment]
Thank you for your response.

I noticed that the issue seemed specific to Quarto markdown files. After experimenting, I was able to get the desired formatting by adding the following to the theme's JSON:

```json
{
  "scope": "markup.heading",
  "settings": {
    "fontStyle": "bold",
    "foreground": "#D0A215"
  }
},
{
  "scope": [
    "punctuation.definition.heading"
  ],
  "settings": {
    "foreground": "#CE5D97"
  }
}
```

Additionally, defining both `entity.name.section` and `entity.name.section.markdown` separately in the theme configuration also seemed to address the issue.

To be honest, theme development and TextMate scopes are not my expertise. However, I found it interesting that Quarto(md)-specific elements, although not explicitly defined, still get formatted correctly by using `.markdown` scopes. It makes me wonder how the default theme handles this as there it is rendered as expected by using `.markdown` scopes.

As for the textmate scopes you asked for:

For the `#` character:
<img width="455" alt="quarto_theme_md_issue" src="https://github.com/kepano/flexoki/assets/68426187/ae6341db-b32e-4a87-bfde-2bb11fc0e888">

For the heading:
<img width="461" alt="quarto_theme_md_issue2" src="https://github.com/kepano/flexoki/assets/68426187/53f225f7-eed7-4f6f-81d4-801f4dddc07f">

**Comment by Railly** [comment]
> It makes me wonder how the default theme handles this as there it is rendered as expected by using .markdown scopes

Yup, you nailed it. I was working on a new theme generator for VSCode yesterday and I can confirm the better defaults you have, the less specificity you need.

I reduced the amount of lines from 1200 to 560 approximately, and obtained a similar, or even a better result.

I'll be releasing an update on this soon.
