### ISSUE TITLE
Started Firefox Themes (help would be appreciated)

### ISSUE THREAD

**Issue by ddogfoodd** [kepano/flexoki#45]
I made a light, a dark and a dynamic theme (or addon) for the Firefox browser.
Links: [Light](https://addons.mozilla.org/en-US/firefox/addon/flexoki-light/), [Dark](https://addons.mozilla.org/en-US/firefox/addon/flexoki-dark/), [Dynamic](https://addons.mozilla.org/en-US/firefox/addon/flexoki-dynamic-theme/)

The [source code for the dynamic theme](https://github.com/jalemann/firefox-flexoki-dynamic-theme) is public.
The light and dark theme use the colors provided there.
However, this is my first try at firefox addons and if anyone knows how to improve things, just send me some hints or pull requests. For example, currently the dynamic version is hard coded to use the light theme between 7am and 10pm, I would rather like to use the preferred appearance provided by the user's OS if possible.

Also note that I tried to stick to the [Flexoki Description](https://stephango.com/flexoki) as strictly as possible, but I had to shift the text colors in the dark theme 2 tones lighter for better contrast and readability. Also there might be alternative ways to use the colors that might look even better. Feel free to discuss changes here or on the repo linked above.

**Comment by ivanhercaz** [comment]
I am already using it since some days ago I am really happy with it, thank you for your work! If I find something strange or that could be a bug, I will report you in your repository ❤️

**Comment by jalemann** [comment]
Next time I find some spare time, I will probably look more into making the theme use the preferred appearance given by the OS. Also I would like to make Thunderbird themes as well, probably not too different to firefox themes.

@kepano Should I keep my repo for now or do you want me to make a pull request and add it to this flexoki repo here? Personally I feel like it would be cleaner to collect everything in the flexoki repo.

**Comment by kepano** [comment]
I have linked to your repo from the readme. If you prefer adding it here, that's okay too. Thanks!
