### ISSUE TITLE
[Feat] Add wezterm light and dark themes

### ISSUE THREAD

**Issue by vihu** [kepano/flexoki#9]
Hello,

Congrats on the release, looks very nice!
Would you consider adding a wezterm light/dark colorscheme port as well?

**Comment by jamesbvaughan** [comment]
I can try to take this. It looks like the proper way to add wezterm themes is via [iTerm2-Color-Schemes](https://github.com/mbadolato/iTerm2-Color-Schemes) so I'll make a PR there.

**Comment by kepano** [comment]
Closed by #20
